Handle NetworkX 2.1 max_weight_matching changes
NetworkX 2.1 introduced two changes in `max_weight_matching()`:

1. Change return of max_weight_matching to be set of edges instead of
   dict of "mates".
2. The set of edges now does not return duplicates (e.g. only u,v and
   not v,u).

See NetworkX commit 22f9451.

This commit makes Chinese Postman Solver handle the new output format.
It prevents the error:

> AttributeError: 'set' object has no attribute 'items'

Maintains backwards compatibility with NetworkX <2.1.

Tested with `test_graph.csv` on NetworkX 1.11 and 2.2. Results were
identical.